# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g @vue/cli'

- script: |
    npm install
    npx vue-cli-service build --dest docs
    # npm run build
  displayName: 'npm install and build'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'conference_mscc_mu'
    sourceFolder: 'docs'
    contents: '**'
    targetFolder: '/home/public/sites/mscc/devcon2020/docs'
    cleanTargetFolder: true
    readyTimeout: '20000'
  displayName: 'Transfer files via SSH'
